### ISSUE TITLE
Error when attempting to download files

### ISSUE THREAD

**Issue by imnotthemessiah** [horrorho/InflatableDonkey#62] opened 2017-05-02 13:31 UTC
Hi all.

I am able to log in to my icloud account and enumerate domains perfectly with inflatabledonkey.

But when I begin the download I get the follwing error:
13:58:44.462 [main] ←[31mWARN ←[0;39m c.g.h.i.util.NSDictionaries - -- parseNSObject() - failed to parse data: The given data is not a property list of a supported format. 0x0a0c45787472612d427435617479122a417070446f6d61696e47726f75702d67726f75702e636f6d2e66616365626f6f6b2e46616365626f6f6b18f9c7def50120fac7def50128fac7def50130bdde1638f50340f503488083025000674415bf62c210c457e8ff25a3ba9be710c000000010146c528000000030100000100000048b05fad171eb5f6fc4c6964c9fe96d92d5a19415c6f2c34767763d6e3c92d786ff483cbed3680c1a81b224cf0531bd73e23e59d32289594de6a37144d74f4f691775dc274bde8710f000000000005b000
13:58:44.462 [ForkJoinPool.commonPool-worker-6] ←[31mWARN ←[0;39m c.g.h.i.util.NSDictionaries - -- parseNSObject() - failed to parse data: The given data is not a property list of a supported format. 0x0a464c6962726172792f4c6f67732f77686174736170702d323031372d30352d30312d31382d32352d35322d3934382d57686174734170702d333339322d6c61756e63682e6c6f67121f417070446f6d61696e2d6e65742e77686174736170702e576861747341707018a2cedef50120a5cfdef50128a5cfdef50130bdf40338f50340f50348a483025000

Can anyone help?

**Comment by Yaldo425** [comment] 2017-05-03 00:11
Unfortunately I am not so experienced in this, but I can tell you that this is caused by a server-side update Apple made. Currently both iPhone Backup Extractor and EPPB do not even work at the moment

**Comment by horrorho** [comment] 2017-06-03 22:17
@imnotthemessiah Hi there. This sounds suspiciously like #54 which was patched a while back. Can you confirm that you've downloaded the latest build and still experience the error?

**Comment by horrorho** [comment] 2017-06-17 03:12
No further input. Suspected duplicate of #54. Closing ticket.

**Closed by horrorho** 2017-06-17 03:12 UTC
